os: linux
dist: bionic
language: c

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:vala-team/next'  # For valac 0.48 on Bionic
    packages:
      - autotools-dev
      - build-essential
      - bzip2
      - debhelper
      - devscripts
      - fakeroot
      - graphviz-dev
      - help2man
      - lcov
      - libgee-0.8-dev
      - libgstreamer1.0-dev
      - libpango1.0-dev
      - libsnapd-glib-dev
      - sharutils   # for uuencode
      - valac
      - valadoc

install:
  - sudo apt install -y --no-install-recommends libsnapd-glib1
  - valac --version
  # Note: at present, it builds OK with Vala 0.40.19.
  - make --version

before_script:
  - ./bootstrap

script:

  # Regular build and test
  - ./configure --disable-dependency-tracking
  # The dependency tracking doesn't work on Travis for some reason ---
  # e.g, https://travis-ci.org/github/cxw42/pfft/builds/718187356
  - make V=1
  - make html V=1
  - make check V=1

  # - make distcheck V=1 DISTCHECK_CONFIGURE_FLAGS=--disable-dependency-tracking
  # --disable-dependency-tracking for #20
  # ... but the automake version on Travis (1.15.1) generates .dirstamp
  # rules for srcdir rather than builddir, so distcheck fails there.
  # This does not bother me enough to be worth fixing at this time.

  # We could make the .deb, but I don't have a deployment provider set up.
  #- dpkg-buildpackage -us -uc

after_failure:
  # Dump the whole development tree into the log
  - 'tar cjf - . | uuencode -em pfft-travis-${TRAVIS_BUILD_ID}.tar.bz2'

after_success:
  - |
    make -j maintainer-clean ; ./bootstrap && \
      ./configure --disable-dependency-tracking --enable-code-coverage USER_VALAFLAGS='-g' CFLAGS='-g -O0' && \
      make -j4 check-code-coverage && \
      bash <(curl -s https://codecov.io/bash) ; : -f pfft-coverage.info
