dist: bionic
language: c

addons:
  apt:
    update: true
    packages:
      - build-essential
      - valac
      - valadoc
      - graphviz-dev
      - help2man
      - autotools-dev
      - libpango1.0-dev
      - libsnapd-glib-dev
      - libgee-0.8-dev
      - libgstreamer1.0-dev

install:
  - sudo apt install -y --no-install-recommends libsnapd-glib1
  - valac --version
  # Note: at present, it builds OK with Vala 0.40.19.

before_script:
  - ./bootstrap
