dist: bionic
language: c

before_install:
    - sudo apt update

install:
    - sudo apt install -y build-essential valac valadoc graphviz-dev help2man
    - sudo apt install -y autotools-dev libpango1.0-dev libsnapd-glib-dev
    - sudo apt install -y --no-install-recommends libsnapd-glib1
    - valac --version

before_script:
    - ./bootstrap
